woowacourse-teams/2022-momo

- backend/src/main/resources/application.yml
- backend/src/test/java/com/woowacourse/momo/acceptance/AcceptanceTest.java
- backend/src/test/java/com/woowacourse/momo/acceptance/CategoryAcceptanceTest.java
- backend/src/test/resources/init.sql
close #31
- 인수테스트의 단일 실행은 통과되나, 전체 실행에서 아래의 테스트가 통과되지 않는 이슈 발생
- 카테고리 목록 조회
- 모임 단일 조회
- 모임 전체 조회
- `init.sql` 파일의 DB 초기화 방식에 문제가 있음을 확인.
- Truncate를 통해 초기화 하던 기존의 방식을, Drop-Create 방식으로 대체
> [BE] 모임 API 기능 - 일부 인수테스트가 통과하지 않는 이슈

- backend/build.gradle
- backend/src/main/resources/application.yml
Issue #38 
인텔리제이가 스프링부트 버전 2.7.1에서 MockMvc, ObjectMapper등의 빈들을 등록하지 못하는 이슈가 있었다.
스프링부트 버전을 2.6.9로 다운그레이드하였다.
> [BE] 스프링부트 버전 오류 & DB 설정 이슈 

- backend/src/main/java/com/woowacourse/momo/group/controller/GroupController.java
- backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
- backend/src/main/java/com/woowacourse/momo/group/service/GroupService.java
- backend/src/main/java/com/woowacourse/momo/group/service/dto/request/GroupRequest.java
- backend/src/main/java/com/woowacourse/momo/group/service/dto/request/GroupRequestAssembler.java
- backend/src/test/java/com/woowacourse/momo/group/controller/GroupControllerTest.java
- backend/src/test/java/com/woowacourse/momo/group/service/GroupServiceTest.java
- backend/src/test/java/com/woowacourse/momo/participant/acceptance/ParticipantAcceptanceTest.java
close #87 
- GroupController에서 모임 수정 및 삭제 기능에서
- `@Authenticated` 를 통해 토큰 검증만 수행하고 있음. (로그인 여부만 확인)
- GroupController의 모임 수정 및 삭제 기능에서
- `@AuthenticationPrincipal`를 통해 토큰으로부터 사용자 ID를 받아와
- 모임의 주최자인지 확인하는 검증 로직을 GroupService에 추가함.
- 모임 생성 API 변경 사항 적용 (hostId 제거) 및 그에 따른 로직 수정
> [BE] 타회원이 주최한 모임의 정보를 수정 및 삭제할 수 있는 이슈 해결

- backend/src/main/java/com/woowacourse/momo/auth/config/AuthConfiguration.java
- backend/src/main/java/com/woowacourse/momo/auth/config/AuthInterceptor.java
- backend/src/main/java/com/woowacourse/momo/config/GlobalWebConfiguration.java
- backend/src/main/java/com/woowacourse/momo/config/WebConfig.java
- backend/src/main/java/com/woowacourse/momo/group/controller/GroupController.java
- backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
- backend/src/main/java/com/woowacourse/momo/group/service/GroupService.java
- backend/src/main/java/com/woowacourse/momo/group/service/dto/request/GroupRequest.java
- backend/src/main/java/com/woowacourse/momo/group/service/dto/request/GroupRequestAssembler.java
- backend/src/test/java/com/woowacourse/momo/group/controller/GroupControllerTest.java
- backend/src/test/java/com/woowacourse/momo/group/service/GroupServiceTest.java
- backend/src/test/java/com/woowacourse/momo/participant/acceptance/ParticipantAcceptanceTest.java
close #92 
- CORS 설정을 `AuthConfiguration`로부터 `GlobalWebConfiguration` 클래스로 분리
- `AuthInterceptor`에서 처리되던 RestDocs 경로 패턴 로직을 `AuthConfiguration`의 interceptor 경로 패턴 적용으로 해결
> [BE] CORS 및 RestDocs 경로 패턴 설정 수정

- frontend/package.json
- frontend/src/components/Animation/NotFoundPageAnimation.tsx
- frontend/src/components/Animation/SpinnerAnimation.tsx
- #127 
**lottie for react 라이브러리 교체**
- 기존에 사용되던 `react-lottie` 라이브러리 지원 종료
- 리액트 18을 지원하는 `lottie-react` 라이브러리로 교체 필요
closed #127
> [FE] lottie-react 버젼 충돌 이슈 해결

- backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
- backend/src/main/java/com/woowacourse/momo/group/service/dto/response/GroupResponseAssembler.java
- backend/src/main/java/com/woowacourse/momo/group/service/dto/response/GroupSummaryResponse.java
- backend/src/test/java/com/woowacourse/momo/acceptance/group/GroupFindAcceptanceTest.java
- Issue #137
모임 전체 조회 반환값에 현재 참여자 수 추가
- API 스펙에 따라 전체 모임 전체 조회시 반환 값에 참여자 수 추가
20분
- close #137
> [BE] 모임 전체 조회 반환값에 현재 참여자 수 추가

- backend/build.gradle
build 폴더에 html 파일을 넣어주는 방식으로 해결하였습니다 🥺
```
copy {
from file("src/main/resources/static")
into file("build/resources/main/static")
}
```
> [BE] RestDocs 빌드 시 파일생성 문제 해결

- backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
- backend/src/main/java/com/woowacourse/momo/group/service/GroupService.java
- backend/src/main/java/com/woowacourse/momo/group/service/dto/request/GroupUpdateRequest.java
- backend/src/main/java/com/woowacourse/momo/group/service/dto/response/GroupPageResponse.java
- backend/src/main/java/com/woowacourse/momo/group/service/dto/response/GroupResponseAssembler.java
- backend/src/main/java/com/woowacourse/momo/member/service/dto/response/MemberResponseAssembler.java
- backend/src/main/java/com/woowacourse/momo/member/service/dto/response/MyInfoResponse.java
- backend/src/test/java/com/woowacourse/momo/acceptance/group/GroupRestHandler.java
- backend/src/test/java/com/woowacourse/momo/acceptance/group/GroupUpdateAcceptanceTest.java
- backend/src/test/java/com/woowacourse/momo/group/controller/GroupControllerTest.java
- backend/src/test/java/com/woowacourse/momo/group/service/GroupServiceTest.java
- backend/src/test/java/com/woowacourse/momo/member/controller/MemberControllerTest.java
- backend/src/test/java/com/woowacourse/momo/member/service/MemberServiceTest.java
> [BE] 모임 수정 로직 추가 및 회원정보 조회 API 반환값 수정

- frontend/src/apis/request/user.ts
- frontend/src/components/Detail/SideBar/Info/ControlButton/index.tsx
- frontend/src/components/Detail/SideBar/Info/index.tsx
- frontend/src/components/Detail/SideBar/Participants/index.tsx
- frontend/src/components/Detail/SideBar/index.tsx
- frontend/src/components/Header/index.tsx
- frontend/src/components/Login/index.tsx
- frontend/src/pages/Detail/index.tsx
- frontend/src/pages/MyInfo/index.tsx
- frontend/src/store/states.ts
- frontend/src/types/user.ts
- #182 
- 로그인 시 또는 access token이 있을 때 사용자 정보를 요청하여 리코일에 저장
- 내 정보 페이지에서 이를 사용하도록 변경
- 해당 모임에 대해 현재 로그인한 사용자의 역할(호스트인지, 현재 참여하고 있는지)을 판단하는 로직 추가
- 모임 상세 페이지의 참여자 목록에서 호스트를 제외한 사람들만 일반 참여자로 보여주도록 변경
closed #182
> [FE] 해당 모임에 대한 사용자의 역할 판단 로직 추가

- frontend/src/apis/request/group.ts
- frontend/src/components/@shared/Calendar/index.styled.ts
- frontend/src/components/@shared/Calendar/index.tsx
- frontend/src/components/Create/Step5/Calendar/index.tsx
- frontend/src/components/Create/Step5/index.tsx
- frontend/src/pages/Create/index.tsx
- frontend/src/styles/global.tsx
- #195 
- 상세 페이지용 / 생성 페이지용 달력 나누기
- duration 기간을 달력에 반영하기
- 일자를 선택했을때 state에 담기 (selected)
- 시간 데이터랑 묶어서 state에 담기 (fixed)
- 추가된 schedule을 유저에게 보여주기
closed #195
> [FE] 모임 생성 시 상세 일정 입력 기능 추가

- frontend/src/components/@shared/Calendar/SelectedDate/index.tsx
- #201 
- 달력에서 일정이 있는 날짜에 호버 시 나오는 모달이 날짜와 겹치면 모달이 계속 여닫히는 현상이 발생하여 이를 해결하고자 함
- 모달에 호버 시 모달이 닫히지 않도록 추가
closed #201
> [FE] 달력 일정 호버 시 모달에 겹치면 모달이 계속 여닫히는 오류 해결

- backend/src/main/java/com/woowacourse/momo/config/AspectConfiguration.java
- backend/src/main/java/com/woowacourse/momo/logging/ExceptionLogging.java
- backend/src/main/java/com/woowacourse/momo/logging/LogFileManager.java
- backend/src/main/java/com/woowacourse/momo/logging/Logging.java
- backend/src/main/resources/application.yml
- backend/src/test/resources/application.yml
젠킨스를 사용하여 배포 자동화 과정에서, 백엔드 배포 서버에는 빌드가 완료된 `.jar` 파일만을 전송한다.
기존의 로그 파일 경로는 소스코드 내에 저장되었기 때문에 잘못된 경로로 인하여 문제가 발생하여 로그 파일의 경로를 수정한다.
- 로그 파일들의 기본 경로 수정
- 배포 서버와 로컬에서의 폴더 구조를 통일시키기 위해 `./momolog` 로 수정
- 다른 로그 파일과 헷갈리지 않도록 `./log` 가 아닌 `./momolog` 사용
- 로그 폴더 내부 경로 수정
- 터미널에서 로그 파일 관리 시 파일 접근이 번거롭다는 피드백 반영
- 로그 파일 경로를 appplication.yml 로 관리
- 테스트 코드 실행 시 로그 파일이 작성되는 것 제거
- 테스트에서도 로그가 작성되는 문제가 발생
- `AspectConfiguration` 에서 설정값을 호출하여 로그를 남기는지에 대한 여부 확인 후 로그 작성
> [BE] 로그 파일의 경로 수정

- frontend/src/utils/date.ts
- #216 
- 오늘 시작인 모임 생성시 마감기한을 설정할 수 없는 오류 해결
closed #216
> [FE] 오늘 시작인 모임 생성시 마감기한을 설정할 수 없는 오류 해결

- backend/src/main/java/com/woowacourse/momo/globalException/exception/ErrorCode.java
- backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java
- backend/src/main/java/com/woowacourse/momo/group/service/GroupService.java
- backend/src/main/java/com/woowacourse/momo/group/service/dto/request/GroupUpdateRequest.java
- backend/src/main/java/com/woowacourse/momo/logging/ExceptionLogging.java
- backend/src/test/java/com/woowacourse/momo/acceptance/group/GroupDeleteAcceptanceTest.java
- backend/src/test/java/com/woowacourse/momo/acceptance/group/GroupRestHandler.java
- backend/src/test/java/com/woowacourse/momo/acceptance/group/GroupUpdateAcceptanceTest.java
- backend/src/test/java/com/woowacourse/momo/group/controller/GroupControllerTest.java
- backend/src/test/java/com/woowacourse/momo/group/domain/group/GroupTest.java
- backend/src/test/java/com/woowacourse/momo/group/service/GroupServiceTest.java
Issue #219 
기존에 모임에 참여자가 있더라도 수정, 삭제가 가능했던 것에서
참여자가 주최자를 제외하고도 존재한다면 수정, 삭제를 할 수 없도록 변경한다.
> [BE] 모임 수정, 모임 삭제 기능을 참여자가 없을 경우에만 가능하도록 변경

- backend/src/main/java/com/woowacourse/momo/auth/config/AuthConfiguration.java
- backend/src/main/java/com/woowacourse/momo/auth/config/OauthConfiguration.java
- backend/src/main/java/com/woowacourse/momo/auth/config/OauthRedirectUrl.java
- backend/src/main/java/com/woowacourse/momo/auth/config/OauthRedirectUrlResolver.java
- backend/src/main/java/com/woowacourse/momo/auth/config/OauthRequestUrl.java
- backend/src/main/java/com/woowacourse/momo/auth/config/OauthRequestUrlResolver.java
- backend/src/main/java/com/woowacourse/momo/auth/config/OauthResolver.java
- backend/src/main/java/com/woowacourse/momo/auth/controller/OauthController.java
- backend/src/main/java/com/woowacourse/momo/auth/service/OauthService.java
- backend/src/main/java/com/woowacourse/momo/auth/support/google/GoogleConnector.java
- backend/src/main/java/com/woowacourse/momo/auth/support/google/GoogleProvider.java
- backend/src/test/java/com/woowacourse/momo/auth/controller/OauthControllerTest.java
Oauth 인증 Redirect Uri 생성방식을 반응형으로 수정
* Oauth 인증에 관하여, 프론트 측과 협의한 내용은 다음 Issue에 적어두었습니다
https://github.com/woowacourse-teams/2022-momo/issues/234
* `@OauthRedirectUrl`이 추가되었습니다.
-> `OauthRedirectUrlResolver#resolveArgument`에서 API 접근자의 프로토콜과 Host를 파싱하여 Redirect URL을 생성합니다.
-> 해당 로직이 필요한 이유는 프론트측의 테스트환경을 보장하기 위함입니다.
-> 테스트를 위한 코드이다 보니.. 추후에 개발이 완료되면 제거할지도?? (open redirect 취약점의 가능성 존재)
* `@OauthRequestUrl`이 추가되었습니다.
-> 사용자로부터 code를 받은 후 구글에게 AccessToken을 요청하는 과정에서
구글이 `사용자에게 code를 넘겨주면서 리다이렉트하는 주소`와 `code와 함께 AccessToken을 요구하는 요청에 담긴 redirect_rul`을 비교하나봅니다. (일치하지 않으면 redirect_uri_mismatch 뜨면서 계속 구글 요청 실패함..ㅂㄷㅂㄷ / 관련자료 찾아도 안나옴 / 추측임) 여튼, 해당 요청을 통과하기 위해 사용자의 Request Url을 파싱해서 구글 요청에 사용합니다.
이번에도 로컬에서는 정상 동작하지만, 배포서버에서는 어떻게 동작할지 확신이 안 드네요ㅜ
더군다나 프론트 측의 로컬 환경도 고려해야 했어서, 더더욱 확신이 안서요
아마도 관련 이슈로 PR이 …
> [BE] Oauth 인증 Redirect Uri 생성방식을 반응형으로 수정

- backend/src/main/java/com/woowacourse/momo/auth/service/OauthService.java
- #247 
이전에 기본 로그인에 대해서 리프레시 토큰을 저장하는 DB에는 Transactional을 붙였었는데 OAuth에 붙이는 것을 빼먹었네요..
바로 추가했습니다
> [BE] OAuth 로그인기능 실패 오류 수정

- backend/src/docs/asciidoc/index.adoc
- backend/src/main/java/com/woowacourse/momo/globalException/exception/ErrorCode.java
- backend/src/main/java/com/woowacourse/momo/storage/controller/ImageController.java
- backend/src/main/java/com/woowacourse/momo/storage/service/StorageService.java
- backend/src/test/java/com/woowacourse/momo/storage/controller/ImageControllerTest.java
- #224 
이미지 업로드 기능을 구현하였습니다~ 경로는 `./image-save/`로 설정해 두었습니다!
테스트의 경우는.. 실제 로컬에 저장해서 테스트하는 것은 좋지 않다고 판단되어 컨트롤러 테스트만 작성해 두었으며 서비스 부분을 MockBean으로 등록 후 모킹하여 처리하였습니다.
약간 혼란스러운 부분은 api의 path를 `/api/images/{image_name}`으로 하는 것 보다는.. 정적 리소스에 대한 접근이라고 보는게 더 맞지 않나 싶어 `/images/{image_name}`이 맞지 않나 싶습니다~
> [BE] 이미지 업로드 기능 구현 

- .github/workflows/backend.yml
- backend/build.gradle
- https://github.com/woowacourse-teams/2022-momo/issues/259
> [BE] SonarQube 서버 구축 및 Github Actions PR 연동

- backend/src/main/java/com/woowacourse/momo/auth/service/TokenService.java
- backend/src/main/java/com/woowacourse/momo/member/domain/Member.java
- backend/src/main/java/com/woowacourse/momo/member/service/MemberService.java
- backend/src/main/java/com/woowacourse/momo/participant/controller/ParticipantController.java
- backend/src/test/java/com/woowacourse/momo/member/service/MemberServiceTest.java
- #307 
두 번 이상 회원 탈퇴 요청 시 500 에러가 발생하였다. 원인은 회원 이름에 `unique` 제약 조건이 걸려 있는데 회원 탈퇴 시 빈값으로 수정하는 과정 때문에 동일한 이름이 존재하여 예외가 발생하였다. 
회원을 탈퇴하더라도 이름을 변경하지 않는다. 로직을 변경하면서 빠트린 토큰 삭제 과정도 추가하였다.
> [BE] 회원 탈퇴 시 에러 발생

- frontend/webpack/webpack.common.js
- #310
- 빌드 시 favicon이 포함되지 않음
- 웹팩 설정에 favicon을 추가하여 빌드될 수 있도록 수정
closed #310
> [FE] 배포 모드에서 favicon이 보이지 않는 오류 해결

- backend/src/main/java/com/woowacourse/momo/group/infrastructure/querydsl/GroupSearchRepositoryImpl.java
fetchjoin을 사용하다 보니 조건을 만족하는 participants만 조회되는 문제가 발생한 것 같습니다.
- 본인이 호스트인 경우 본인만 조회되므로 1명
- 본인이 참여자인 경우 호스트인 사람 + 참여자에 본인 한명 = 2명
일단 fetchjoin을 풀고, leftjoin만 걸려있다 보니 중복 데이터가 나타나는 문제가 있어 distinct를 따로 걸어 두었습니다.
> [BE] 모임 참여인원이 실제와 다르게 출력되는 현상 해결

- backend/src/main/java/com/woowacourse/momo/auth/config/RefreshTokenAuthInterceptor.java
- backend/src/main/java/com/woowacourse/momo/auth/domain/Token.java
- backend/src/test/java/com/woowacourse/momo/auth/service/TokenServiceTest.java
- backend/src/test/java/com/woowacourse/momo/auth/support/JwtTokenProviderTest.java
- #377 
Access Token만료 후, Refresh Token을 통한 재접근 플로우가 작동되지 않았다.
백엔드의 로직 확인 결과 백엔드 상의 오류는 발견하지 못하였다.
> 해당 문제는 프론트쪽에서 `AUTH_ERROR_001`에러 코드를 받았을 때, 리프레시 토큰을 통해 엑세스 토큰을 요청 후 사용하도록 수정을 해야하는 것으로 판단된다.
계획대로 `AUTH_ERROR_001`을 던져주는 것과 Refresh Token 재발급 API에 대한 확인을 완료하였다.
- 코드를 확인하며 Token의 기간 만료시 발생하는 예외에 대한 테스트 코드가 없어서 테스트 추가
- 그 외에도 몇몇 테스트 코드 추가
- 항상 `!`를 통해 항상 반대의 값을 필요로 하는 로직을 반대로 변경
- Token객체의 누락된 `@JoinColumn`의 외래키 명시
> [BE] Access Token만료 후, Refresh Token을 통한 재접근 불가 오류

- backend/src/main/java/com/woowacourse/momo/group/domain/Group.java
- backend/src/main/java/com/woowacourse/momo/group/infrastructure/querydsl/ConditionFilter.java
- backend/src/main/java/com/woowacourse/momo/group/service/GroupModifyService.java
- backend/src/test/java/com/woowacourse/momo/acceptance/group/GroupDeleteAcceptanceTest.java
- backend/src/test/java/com/woowacourse/momo/acceptance/group/GroupUpdateAcceptanceTest.java
- backend/src/test/java/com/woowacourse/momo/group/domain/GroupTest.java
- backend/src/test/java/com/woowacourse/momo/group/infrastructure/querydsl/GroupSearchRepositoryTest.java
- backend/src/test/java/com/woowacourse/momo/group/service/GroupModifyServiceTest.java
회의 결과에 따라 마감로직을 변경하였습니다. 
1. 모임 조회 시 참여자의 수가 가득 찼는지 확인하는 로직을 제거하였습니다.
2. 모임 수정 시 참여자의 수가 가득 찼는지 확인하는 로직을 제거하였습니다.
3. Querydsl 로직 중 참여자 수로 마감 여부를 검사하는 로직을 제거하였습니다.
4. (1)로 인해 영향받는 테스트 코드를 최대한 제거하지 않고 테스트 자체를 변경하였습니다.
> [BE] 마감일이 지나지 않아도 참여자 정원이 가득차면 수정/삭제할 수 없는 현상

- backend/src/main/java/com/woowacourse/momo/group/domain/Group.java
- backend/src/test/java/com/woowacourse/momo/group/domain/favorite/FavoriteTest.java
- backend/src/test/java/com/woowacourse/momo/group/domain/favorite/FavoritesTest.java
- backend/src/test/java/com/woowacourse/momo/group/domain/search/GroupSearchRepositoryTest.java
- backend/src/test/java/com/woowacourse/momo/group/service/LikeServiceTest.java
- #375 
모집이 마감된 모임에 대하여 찜하기/찜취소 기능 에러가 발생하는 현상
- 마감된 모집에 대하여 찜하기/찜 취소 기능이 불가능하던 오류 수정
- 부족했던 찜 기능 테스트 코드 추가
closed #375
> [BE] 모집이 마감된 모임에 대하여 찜하기/찜취소 기능 에러가 발생하는 현상

- backend/src/main/java/com/woowacourse/momo/group/infrastructure/querydsl/ConditionFilter.java
- backend/src/main/java/com/woowacourse/momo/group/infrastructure/querydsl/GroupSearchRepositoryImpl.java
- #383
하이버네이트 특성상 `OneToMany`관계에서 `fetchJoin()`과 `limit()`을 같이 사용하니 쿼리상으로는 Full Scan을 한 후, 페이지네이션은 JVM상에서 데이터를 필터링 하는 방법으로 구동이 되었다.
**적용한 결과**
우리의 쿼리 특성상 필터링 기능을 사용하며 Group, Participant, Favorite 테이블을 Join하며 필터링 및 결과 조회를 진행하고 있다. Favorite과 Group의 연관관계를 역으로 진행하여 Favorite테이블을 통해 조회를 한다고 하여도, Participant 테이블을 Join하는 과정에서 OneToMany가 발생하여 문제 해결이 안된다.
```java
@Override
public Page<Group> findLikedGroups(SearchCondition condition, Member member, Pageable pageable) {
List<Group> groups = queryFactory
.select(favorite.group)
.from(favorite)
.innerJoin(favorite.group, group)
.leftJoin(group.participants.participants, participant) // 해당 과정에서 OneToMany가 발생
.fetchJoin()
.where(
favorite.member.eq(member),
conditionFilter.filterByCondition(condition)
)
.groupBy(favorite.group.id) …
```
> [BE] QueryDSL 이용하여 pagination 할 때 limit 이 설정되지 않는 현상

- frontend/src/components/Card/index.tsx
- frontend/src/constants/message.ts
- frontend/src/pages/Detail/SideBar/Info/index.tsx
- frontend/src/pages/Detail/SideBar/Participants/index.tsx
- #372 
- 탈퇴한 회원의 이름은 빈 문자열이 되는 형식으로 바뀌었기에, 이에 맞게 프론트에서 참여자 중 탈퇴한 회원이 있을 경우에 이를 표시해주도록 변경
closed #372
> [FE] 탈퇴한 아이디로 다시 회원가입을 할 수 없는 현상

- backend/src/main/java/com/woowacourse/momo/group/infrastructure/querydsl/GroupSearchRepositoryImpl.java
- backend/src/test/java/com/woowacourse/momo/group/controller/GroupSearchControllerTest.java
- backend/src/test/java/com/woowacourse/momo/group/service/GroupSearchServiceTest.java
- #391 
페이지네이션을 하는 과정에서 전체 데이터를 조회하는 쿼리를 분리하지 않았다.
그 결과 `전체 데이터==조회한 데이터의 수(최대 12개)`의 상황이 나와서 항상 hasNextPage가 false였다.
```java
JPAQuery<Long> countQuery = queryFactory
.select(group.count())
.from(group)
.leftJoin(group.participants.participants, participant)
.innerJoin(group.favorites.favorites, favorite)
.where(
group.id.in(likedGroupIds)
);
```
모임들을 조회하는 메서드들에 해당 쿼리를 추가하며 문제를 해결하였다.
찜한 모임 목록을 조회할 때, 엔티티 조회 과정에서 distinct를 붙이지 않아 participant의 수만큼 모임이 조회되는 오류가 발생하여 해결하였다.
찜 목록 조회를 할 때, 찜한 모임의 ID를 모두 조회한 후 해당 ID를 통해 모임 엔티티를 조회하였다. 
하지만 이때 찜한 모임의 id를 조회하는 과정에서 아래와 같이 불필요하게 participant를 leftjoin하였다. 그 결과 데이터의 뻥튀기가 발생하며 반환되는 엔티티의 수가 예상과는 다르게 반환되었다.
```java
public List<Long> findLikedGroupIds(SearchCondition condition, Member member, Pageable pageable) {
return queryFactory
.select(group.id) …
```
> [BE] 페이지네이션 과정에서 Page의 hasNext()가 잘못 나오는 오류 + 찜 조회 기능 오류

- backend/src/main/java/com/woowacourse/momo/group/domain/Group.java
- 모임진행 유효성 검증 절차 순서를 변경함
- 기존: 조기마감여부 확인 후 마감기한 확인
- 변경: 마감기한 확인 후 조기마감여부 확인 
- #402
> [BE] 조기마감된 모임에 대한 에러코드가 마감기한이 지나도 동일한 이슈

- frontend/src/pages/Main/index.tsx
- #406 
- 검색 시 기존에 존재하던 모임에 덮어씌우도록 추가
closed #406
> [FE] 메인 페이지에서 검색 시 새롭게 들어온 모임 목록이 기존 모임 목록에 추가되는 오류 해결

- backend/src/main/java/com/woowacourse/momo/MomoApplication.java
- backend/src/main/java/com/woowacourse/momo/global/config/TimeConfig.java
- #408 
모임에서 설정한 일정과 모집 기간의 날짜가 하루 전날로 저장 및 조회되었다.
프로젝트의 전체 TimeZone 을 UTC+09:00으로 설정해 주었다.
> [BE] 모임의 일정이 설정한 날짜보다 하루 전날로 저장되는 현상 해결

- backend/src/main/java/com/woowacourse/momo/auth/config/AuthConfiguration.java
- backend/src/main/java/com/woowacourse/momo/global/exception/ControllerAdvice.java
- backend/src/main/java/com/woowacourse/momo/global/exception/exception/GlobalErrorCode.java
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application-local.yml
- backend/src/main/resources/application-prod.yml
- backend/src/main/resources/application-test.yml
- https://github.com/woowacourse-teams/2022-momo/issues/412
- 기능추가 : 지원하지 않는 API 요청에 대한 예외처리
- 에러 코드 등록
- `UNHANDLED_API_ERROR(404, "NOT_FOUND", "지원하지 않는 API 요청입니다.")`
- application.yml 설정값 등록
- mvc.throw-exception-if-no-handler-found: true
- DispatcherServlet에서 해당 상황을 Exception Throw할 것인지 지정
- web.resources.add-mappings: false
- no handler 상황에서 ResourceHttpRequestHandler를 반환하지 않도록 지정
- 해당 설정을 해야 AuthInterceptor의 `(HandlerMethod) handler` 에서 발생하던
- ClassCastException을 해결할 수 있었고 ControllerAdvise에서 NoHandlerFoundException 예외를 탐지할 수 있었음.
- 참고: [SpringBoot 존재하지 않는 API 요청의 응답 커스마이징하기](https://tecoble.techcourse.co.kr/post/2021-11-24-spring-customize-unhandled-api/)
- 리팩토링 : ControllerAdvise 중복 로직 메서드 추출
- application.yml 중복 제거 및 구조 변경은 별도의 이슈로 진행하겠습니다~
> [BE] 지원하지 않은 API 요청에 대해 404 반환

- backend/src/main/java/com/woowacourse/momo/group/domain/participant/Capacity.java
- backend/src/main/java/com/woowacourse/momo/group/domain/participant/Participants.java
- backend/src/main/java/com/woowacourse/momo/group/service/ParticipateService.java
- backend/src/test/java/com/woowacourse/momo/group/domain/participant/CapacityTest.java
> [BE] 모임 참여 요청이 동시에 왔을 때 참여 인원을 초과하는 문제

- backend/src/main/java/com/woowacourse/momo/auth/exception/AuthErrorCode.java
- backend/src/main/java/com/woowacourse/momo/member/domain/MemberRepository.java
- backend/src/main/java/com/woowacourse/momo/member/exception/MemberErrorCode.java
- backend/src/main/java/com/woowacourse/momo/member/service/MemberService.java
- backend/src/test/java/com/woowacourse/momo/auth/service/AuthServiceTest.java
- backend/src/test/java/com/woowacourse/momo/favorite/controller/FavoriteControllerTest.java
- backend/src/test/java/com/woowacourse/momo/group/controller/ParticipateControllerTest.java
- backend/src/test/java/com/woowacourse/momo/member/service/MemberServiceTest.java
🚀 기능 추가 설명
- https://github.com/woowacourse-teams/2022-momo/issues/414
- 위의 PR에서 반영했던 `사용자 아이디 Unique 적용`에 대해 유효성 검증 로직을 추가
> [BE] 동일한 사용자 이름으로 회원가입하는 경우에 대한 유효성 검증

- backend/src/main/java/com/woowacourse/momo/group/controller/dto/request/GroupRequestAssembler.java
모임 수정 API 요청 정보로부터 데이터를 잘못 사용하고 있음을 코드 상 파악했고,
3번째 인자에 잘못 지정된 getBuildingName()을 getDetail()로 변경했다
> [BE] 모임 장소 수정 시 세부내용이 잘못 업데이트 되는 이슈 발생

- backend/src/main/java/com/woowacourse/momo/group/domain/search/dto/GroupSummaryRepositoryResponse.java
- backend/src/main/java/com/woowacourse/momo/group/service/GroupSearchService.java
- backend/src/test/java/com/woowacourse/momo/group/service/GroupSearchServiceTest.java
- #481 
모임 이미지 정보 조회할 때 이미지 정보가 `null` 일 경우 **모임의 기본 이미지로 대체**한다.
> [BE] 모임 목록 조회 시 이미지 정보가 없으면 빈값으로 보여지는 현상

- frontend/src/apis/request/group.ts
- frontend/src/components/ImageDropBox/index.tsx
- frontend/src/pages/Detail/index.tsx
- frontend/src/pages/Detail/versions/Desktop/Content/EditMode/index.tsx
- frontend/src/pages/Detail/versions/Desktop/Content/index.tsx
- frontend/src/pages/Detail/versions/Desktop/ControlButton/index.tsx
- frontend/src/pages/Detail/versions/Desktop/index.tsx
- frontend/src/pages/Detail/versions/Mobile/Content/EditMode/index.tsx
- frontend/src/pages/Detail/versions/Mobile/Content/index.tsx
- frontend/src/pages/Detail/versions/Mobile/ControlButton/index.tsx
- frontend/src/pages/Detail/versions/Mobile/index.tsx
- frontend/src/store/states.ts
- frontend/src/types/data.ts
- #501 
- 모임 상세 정보 응답에는 id 값이 없으나, 프론트엔드 코드에는 존재하는 것을 확인하여 이를 제거하고자 함
- GroupDetailData 타입에서 id를 제거하고 GroupSummary 타입에 id 추가
closed #501
> [FE] 모임 상세 정보 타입에서 id 제거

- backend/src/main/java/com/woowacourse/momo/storage/exception/GroupImageErrorCode.java
- backend/src/main/java/com/woowacourse/momo/storage/service/GroupImageService.java
- backend/src/main/java/com/woowacourse/momo/storage/support/ImageConnector.java
- backend/src/test/java/com/woowacourse/momo/group/service/GroupSearchServiceTest.java
- backend/src/test/java/com/woowacourse/momo/storage/controller/GroupImageControllerTest.java
- backend/src/test/java/com/woowacourse/momo/storage/service/GroupImageServiceTest.java
- #488 
이전에 사용했던 FileSystemResource 객체는 실제 존재하는 파일을 요구헀다. 이미지 서버로 전송하던 과정에서 파일을 읽는 과정이 있었고, 존재하는 파일이 아니라서 예외가 발생하였다. 
임의로 Resource 를 만들어 이미지 서버에 보내는 것이 아닌, MultipartFile 에서 제공하는 getResource() 메서드를 사용하였다..
> [BE] 모임 썸네일 수정 시 오류가 발생하는 현상

- backend/src/main/java/com/woowacourse/momo/group/domain/search/GroupSearchRepository.java
- backend/src/main/java/com/woowacourse/momo/group/service/ParticipateService.java
- https://github.com/woowacourse-teams/2022-momo/issues/498
- `ParticipateService#participate`에 지정되어 있던 synchronized 키워드를 제거하고
- `GroupSearchRepository#findById`에 `@Lock(value = LockModeType.PESSIMISTIC_WRITE)` 비관적 lock 지정함
- `ParticipateService#findParticipants`에서 `GroupFindService#findByIdWithHostAndSchedule`를 사용하도록 수정
> [BE] 동시성 문제 해결
