frontend/.babelrc.js, frontend/.eslintrc.js, frontend/.gitignore, frontend/.prettierrc.js, frontend/.storybook/main.js, frontend/.storybook/preview.js, frontend/README.md, frontend/package-lock.json, frontend/package.json, frontend/public/index.html, frontend/src/App.tsx, frontend/src/components/Footer.tsx, frontend/src/components/Header.tsx, frontend/src/index.tsx, frontend/src/pages/Main/index.tsx, frontend/tsconfig.json, frontend/webpack.config.js
Issue: https://github.com/woowacourse-teams/2022-momo/issues/7
- react
- typescript
- webpack
- babel
- eslint
- prettier
- emotion
- storybook
=> [FE] 프론트엔드 환경 구축

backend/src/main/java/com/woowacourse/momo/domain/group/Group.java, backend/src/test/java/com/woowacourse/momo/repository/GroupRepositoryTest.java
=> [BE] 모임 도메인 누락된 필드 추가

backend/build.gradle, backend/src/main/java/com/woowacourse/momo/controller/CategoryController.java, backend/src/main/java/com/woowacourse/momo/controller/GroupController.java, backend/src/main/java/com/woowacourse/momo/domain/group/Day.java, backend/src/main/java/com/woowacourse/momo/domain/group/Duration.java, backend/src/main/java/com/woowacourse/momo/domain/group/Group.java, backend/src/main/java/com/woowacourse/momo/domain/group/Schedule.java, backend/src/main/java/com/woowacourse/momo/domain/group/Schedules.java, backend/src/main/java/com/woowacourse/momo/domain/member/Member.java, backend/src/main/java/com/woowacourse/momo/service/CategoryService.java, backend/src/main/java/com/woowacourse/momo/service/GroupService.java, backend/src/main/java/com/woowacourse/momo/service/dto/CategoryResponse.java, backend/src/main/java/com/woowacourse/momo/service/dto/request/DurationRequest.java, backend/src/main/java/com/woowacourse/momo/service/dto/request/GroupRequest.java, backend/src/main/java/com/woowacourse/momo/service/dto/request/GroupUpdateRequest.java, backend/src/main/java/com/woowacourse/momo/service/dto/request/ScheduleRequest.java, backend/src/main/java/com/woowacourse/momo/service/dto/request/TimeRequest.java, backend/src/main/java/com/woowacourse/momo/service/dto/response/DurationResponse.java, backend/src/main/java/com/woowacourse/momo/service/dto/response/GroupResponse.java, backend/src/main/java/com/woowacourse/momo/service/dto/response/MemberResponse.java, backend/src/main/java/com/woowacourse/momo/service/dto/response/ScheduleResponse.java, backend/src/main/java/com/woowacourse/momo/service/dto/response/TimeResponse.java, backend/src/test/java/com/woowacourse/momo/acceptance/AcceptanceTest.java, backend/src/test/java/com/woowacourse/momo/acceptance/CategoryAcceptanceTest.java, backend/src/test/java/com/woowacourse/momo/acceptance/GroupAcceptanceTest.java, backend/src/test/java/com/woowacourse/momo/acceptance/RestAssuredConvenienceMethod.java, backend/src/test/java/com/woowacourse/momo/repository/GroupRepositoryTest.java, backend/src/test/java/com/woowacourse/momo/service/CategoryServiceTest.java, backend/src/test/resources/init.sql
=> [BE] 모임 API 기능 구현

backend/src/main/java/com/woowacourse/momo/auth/config/AuthConfiguration.java, backend/src/main/java/com/woowacourse/momo/auth/config/AuthInterceptor.java, backend/src/main/java/com/woowacourse/momo/auth/config/Authenticated.java, backend/src/main/java/com/woowacourse/momo/group/controller/GroupController.java, backend/src/main/java/com/woowacourse/momo/member/controller/MemberController.java, backend/src/test/java/com/woowacourse/momo/common/acceptance/RestHandler.java, backend/src/test/java/com/woowacourse/momo/group/acceptance/GroupAcceptanceTest.java
=> [BE] Annotation 기반의 Interceptor를 통한 API 인증 처리

backend/src/test/java/com/woowacourse/momo/category/controller/CategoryControllerTest.java, backend/src/test/java/com/woowacourse/momo/group/controller/GroupControllerTest.java, backend/src/test/java/com/woowacourse/momo/member/controller/MemberControllerTest.java
=> [BE] 누락된 Controller 테스트 작성

backend/src/test/java/com/woowacourse/momo/group/controller/GroupControllerTest.java
=> [BE] 실패 테스트 코드 수정

.github/workflows/backend.yml
=> [BE] CI Github Action 추가

backend/src/main/java/com/woowacourse/momo/auth/config/AuthConfiguration.java
=> [BE] CORS 접근 허용

.github/workflows/backend.yml, backend/src/docs/asciidoc/index.adoc, backend/src/main/java/com/woowacourse/momo/auth/config/AuthConfiguration.java, backend/src/main/java/com/woowacourse/momo/auth/config/AuthInterceptor.java, backend/src/main/java/com/woowacourse/momo/globalException/ControllerAdvice.java, backend/src/main/java/com/woowacourse/momo/globalException/dto/response/ExceptionResponse.java, backend/src/main/java/com/woowacourse/momo/group/controller/GroupController.java, backend/src/main/java/com/woowacourse/momo/group/domain/group/Group.java, backend/src/main/java/com/woowacourse/momo/group/service/GroupService.java, backend/src/main/java/com/woowacourse/momo/group/service/dto/response/GroupIdResponse.java, backend/src/main/java/com/woowacourse/momo/group/service/dto/response/GroupResponseAssembler.java, backend/src/main/java/com/woowacourse/momo/member/dto/response/MemberResponseAssembler.java, backend/src/main/java/com/woowacourse/momo/participant/controller/ParticipantController.java, backend/src/main/java/com/woowacourse/momo/participant/domain/Participant.java, backend/src/main/java/com/woowacourse/momo/participant/service/ParticipantService.java, backend/src/test/java/com/woowacourse/momo/auth/controller/AuthControllerTest.java, backend/src/test/java/com/woowacourse/momo/category/controller/CategoryControllerTest.java, backend/src/test/java/com/woowacourse/momo/common/acceptance/RestHandler.java, backend/src/test/java/com/woowacourse/momo/group/controller/GroupControllerTest.java, backend/src/test/java/com/woowacourse/momo/group/domain/group/GroupRepositoryTest.java, backend/src/test/java/com/woowacourse/momo/member/controller/MemberControllerTest.java, backend/src/test/java/com/woowacourse/momo/participant/acceptance/ParticipantAcceptanceTest.java, backend/src/test/java/com/woowacourse/momo/participant/service/ParticipantServiceTest.java
=> [BE] RestDocs 적용하기

backend/src/main/java/com/woowacourse/momo/group/service/GroupFindService.java, backend/src/main/java/com/woowacourse/momo/group/service/GroupService.java, backend/src/main/java/com/woowacourse/momo/member/service/MemberFindService.java, backend/src/main/java/com/woowacourse/momo/member/service/MemberService.java, backend/src/main/java/com/woowacourse/momo/participant/service/ParticipantService.java, backend/src/test/java/com/woowacourse/momo/group/service/GroupFindServiceTest.java, backend/src/test/java/com/woowacourse/momo/member/service/MemberFindServiceTest.java, backend/src/test/java/com/woowacourse/momo/participant/acceptance/ParticipantAcceptanceTest.java, backend/src/test/java/com/woowacourse/momo/participant/service/ParticipantServiceTest.java
=> [BE] 조회 로직 리팩토링

.github/workflows/backend.yml
=> [BE] CI Github Action 오류 수정

backend/src/main/java/com/woowacourse/momo/group/service/dto/request/GroupRequest.java, backend/src/main/java/com/woowacourse/momo/group/service/dto/request/GroupUpdateRequest.java, backend/src/main/java/com/woowacourse/momo/group/service/dto/response/GroupResponse.java, backend/src/test/java/com/woowacourse/momo/group/acceptance/GroupAcceptanceTest.java, backend/src/test/java/com/woowacourse/momo/group/controller/GroupControllerTest.java, backend/src/test/java/com/woowacourse/momo/group/domain/group/GroupRepositoryTest.java, backend/src/test/java/com/woowacourse/momo/participant/acceptance/ParticipantAcceptanceTest.java
close #99 
- `GroupRequest` `GroupUpdateRequest` `GroupResponse` 의 `deadline` 필드에 지정되어 있는  
`@JsonFormat`의 패턴을 다음과 같이 수정 (`yyyy-MM-dd HH:mm` -> `yyyy-MM-dd'T'HH:mm`)
=> [BE] JSON DateTime 형식 불일치로 인한 에러 발생

backend/src/main/java/com/woowacourse/momo/category/domain/Category.java, backend/src/main/resources/application.yml, backend/src/main/resources/data.sql, backend/src/test/java/com/woowacourse/momo/category/controller/CategoryControllerTest.java, backend/src/test/java/com/woowacourse/momo/group/domain/group/GroupRepositoryTest.java, backend/src/test/java/com/woowacourse/momo/member/domain/MemberRepositoryTest.java, backend/src/test/resources/application.yml
=> [BE] 더미 데이터 작성

frontend/src/components/Login/index.tsx, frontend/src/components/Signup/index.styled.ts, frontend/src/components/Signup/index.tsx, frontend/src/components/Signup/validate.ts, frontend/src/constants/message.ts, frontend/src/utils/errorController.ts
- #149 
- 회원가입 시 유효성 검사
- 로그인 시 유효성 검사
- 회원가입 시 에러 메시지 세분화
- 로그인 시 에러 메시지 세분화
- 로그인 input 비제어 컴포넌트화
closed #149
=> [FE] 회원가입, 로그인 시 유효성 검사 및 에러 메시지 세분화

.github/workflows/backend.yml
=> [BE] 서브모듈 도입을 위한 Github Action 수정

backend/src/main/java/com/woowacourse/momo/group/service/GroupService.java, backend/src/main/java/com/woowacourse/momo/group/service/dto/response/GroupPageResponse.java, backend/src/main/java/com/woowacourse/momo/group/service/dto/response/GroupResponseAssembler.java
모임 목록 조회에 pageNumber 필드가 필요하다고 해서 추가하였습니다~
=> [BE] 모임 목록 조회 pageNumber 필드 추가 

backend/src/docs/asciidoc/index.adoc, backend/src/main/java/com/woowacourse/momo/group/controller/GroupController.java, backend/src/main/java/com/woowacourse/momo/group/domain/group/GroupRepository.java, backend/src/main/java/com/woowacourse/momo/group/service/GroupFindService.java, backend/src/main/java/com/woowacourse/momo/group/service/GroupService.java, backend/src/test/java/com/woowacourse/momo/acceptance/group/GroupFindAcceptanceTest.java, backend/src/test/java/com/woowacourse/momo/acceptance/group/GroupRestHandler.java, backend/src/test/java/com/woowacourse/momo/group/controller/GroupControllerTest.java, backend/src/test/java/com/woowacourse/momo/group/service/GroupFindServiceTest.java, backend/src/test/java/com/woowacourse/momo/group/service/GroupServiceTest.java
issue #165 
기능 구현을 끝마쳤으니.. 리뷰 부탁드립니다 🥕
close #165
=> [BE] 사용자가 참여한 그룹 목록 조회 api 구현 

.github/workflows/backend.yml, .gitmodules, backend/src/main/resources/application-security.yml, backend/src/main/resources/application.yml
보안문제로 외부에 공개되지 않아야 하는 정보에 대하여,  
Git submodule을 이용하여 private으로 관리
private repository : https://github.com/2022-momo/security
close #158
=> [BE] 서브모듈 도입

frontend/src/components/@shared/Calendar/SelectedDate/index.styled.ts, frontend/src/components/@shared/Calendar/SelectedDate/index.tsx, frontend/src/components/@shared/Calendar/index.styled.ts, frontend/src/components/@shared/Calendar/index.tsx, frontend/src/components/Create/Step5/index.tsx, frontend/src/hooks/useCreateState.ts, frontend/src/pages/Create/index.tsx, frontend/src/utils/date.ts
- #157 
달력에 선택된 날짜를 시각적으로 보여줄 수 있도록 추가
- Full Calendar
- Hovering 시 조그만 시간 모달
closed #157
=> [FE] 달력에 선택된 날짜를 보여줄 수 있는 기능 추가

frontend/src/apis/request/group.ts, frontend/src/components/Detail/SideBar/Info/ControlButton/index.tsx, frontend/src/constants/message.ts, frontend/src/constants/path.ts
- #179 
모임 상세 페이지에 모임 모집 마감 기능 추가
closed #179
=> [FE] 모임 모집 마감 기능 구현

frontend/package.json, frontend/src/utils/date.ts, frontend/src/utils/utils.test.ts
- #177 
utils의 `date` 함수 테스트 코드 작성
closed #177
=> [FE] utils 함수 테스트 코드 작성

frontend/package-lock.json, frontend/src/components/Login/index.tsx
- #189 
- access token을 저장한 후 회원정보를 요청하도록 순서 변경
closed #189
=> [FE] 로그인 시 회원정보를 제대로 가져오지 못하는 오류 해결

frontend/src/components/Detail/SideBar/Info/ControlButton/index.tsx
- #186 
- 호스트 입장
- 모임 모집을 마감했을 경우
- 참여자 입장
- 모임에 참여했을 경우
- 모임 참여를 취소했을 경우
closed #186
=> [FE] 모임 상태가 변경되면 모임 상세 페이지 리렌더링

frontend/src/apis/axios.ts
=> [FE] API 주소 업데이트

backend/src/main/resources/application.yml
서브모듈 commit hash 링크가 과거 이력을 가리키고 있었음.
서브모듈의 최신 과거 이력을 가리키도록 수정.
=> [BE] 배포 서버 재시작 시 DB 초기화되는 현상 발생

frontend/src/components/Card/index.tsx, frontend/src/components/Detail/Content/index.tsx, frontend/src/components/Detail/SideBar/Info/ControlButton/index.styled.ts, frontend/src/components/Detail/SideBar/Info/ControlButton/index.tsx, frontend/src/components/Detail/SideBar/Info/index.tsx, frontend/src/components/Detail/SideBar/index.tsx, frontend/src/pages/Detail/index.tsx, frontend/src/types/data.ts
- #184 
- 마감된 모임에 비활성화된 버튼 추가
- 마감된 모임은 상세 페이지 설명에 모집 마감 표시
- 마감된 모임은 메인 화면에서 마감 표시
- 설명이 없는 모임은 description 영역 제거
closed #184
=> [FE] 마감된 모임에 대해 상태 반영

backend/src/docs/asciidoc/index.adoc
RestDocs에 누락된 문서를 추가하고 목차를 따로 추가하였습니다~
=> [BE] RestDocs 목차 추가

frontend/src/components/RecommendGroups/index.tsx
- #207 
- 마지막 페이지의 데이터도 보여주도록 추가
closed #207
=> [FE] 무한 스크롤 시 마지막 페이지의 데이터가 나오지 않는 오류 해결

frontend/src/components/@shared/Calendar/index.styled.ts
- #214 
- 선택한 날짜를 오늘 날짜보다 먼저 하이라이팅 되도록 수정
closed #214
=> [FE] 달력 날짜 하이라이팅 우선순위 변경

frontend/src/components/@shared/TopButton/index.styled.ts, frontend/src/components/@shared/TopButton/index.tsx, frontend/src/pages/Main/index.tsx
- #230 
- 무한 스크롤이 있는 페이지에 TOP 버튼 추가
- 현재는 메인 페이지만 존재
closed #230
=> [FE] TOP 버튼 구현

frontend/.gitignore, frontend/package-lock.json, frontend/package.json, frontend/src/apis/axios.ts, frontend/webpack/webpack.common.js, frontend/webpack/webpack.development.js, frontend/webpack/webpack.production.js
=> [FE] 환경변수 설정

frontend/src/components/Create/Navigator/Button/index.styled.ts, frontend/src/components/Create/Navigator/Button/index.tsx, frontend/src/components/Create/Navigator/index.tsx
=> [FE] 모임 생성 페이지에서 각 스텝에 대해 모달로 띄워주는 호버 이벤트 추가

frontend/public/index.html, frontend/src/components/@shared/Snackbar/index.styled.ts, frontend/src/components/@shared/Snackbar/index.tsx, frontend/src/components/Detail/SideBar/Info/ControlButton/index.tsx, frontend/src/components/Login/index.tsx, frontend/src/components/Modal/index.tsx, frontend/src/components/Portal/index.tsx, frontend/src/components/Signup/index.tsx, frontend/src/hooks/useClosingState.ts, frontend/src/hooks/useSnackbar.ts, frontend/src/layouts/Page/index.tsx, frontend/src/pages/Auth/index.tsx, frontend/src/pages/MyInfo/index.tsx, frontend/src/store/states.ts, frontend/src/types/condition.ts
- #256 
- 스낵바 컴포넌트 구현
- 성공 alert을 스낵바로 대체
closed #256
=> [FE] 스낵바 구현

frontend/src/apis/request/auth.ts, frontend/src/components/Header/User/index.tsx, frontend/src/constants/message.ts, frontend/src/constants/path.ts
- #266 
- 로그아웃 시 서버 요청
- 액세스 토큰 만료 시 로그아웃
closed #266
=> [FE] 로그아웃 요청 추가

backend/src/docs/asciidoc/index.adoc
=> [BE] 모임 수정 API Docs 활성화

backend/src/docs/asciidoc/index.adoc, backend/src/main/java/com/woowacourse/momo/category/domain/Category.java, backend/src/main/java/com/woowacourse/momo/global/exception/exception/ErrorCode.java, backend/src/main/java/com/woowacourse/momo/group/controller/GroupController.java, backend/src/main/java/com/woowacourse/momo/group/domain/group/GroupRepository.java, backend/src/main/java/com/woowacourse/momo/group/domain/group/GroupSpecification.java, backend/src/main/java/com/woowacourse/momo/group/service/GroupFindService.java, backend/src/main/java/com/woowacourse/momo/group/service/GroupService.java, backend/src/main/java/com/woowacourse/momo/group/service/dto/request/GroupFindRequest.java, backend/src/main/java/com/woowacourse/momo/member/service/MemberService.java, backend/src/main/java/com/woowacourse/momo/participant/service/ParticipantService.java, backend/src/test/java/com/woowacourse/momo/acceptance/group/GroupFindAcceptanceTest.java, backend/src/test/java/com/woowacourse/momo/acceptance/group/GroupRestHandler.java, backend/src/test/java/com/woowacourse/momo/acceptance/member/MemberAcceptanceTest.java, backend/src/test/java/com/woowacourse/momo/category/domain/CategoryTest.java, backend/src/test/java/com/woowacourse/momo/fixture/DurationFixture.java, backend/src/test/java/com/woowacourse/momo/group/controller/GroupControllerTest.java, backend/src/test/java/com/woowacourse/momo/group/domain/group/GroupFindRepositoryTest.java, backend/src/test/java/com/woowacourse/momo/group/domain/group/GroupRepositoryTest.java, backend/src/test/java/com/woowacourse/momo/group/domain/group/GroupTest.java, backend/src/test/java/com/woowacourse/momo/group/service/GroupFindServiceTest.java, backend/src/test/java/com/woowacourse/momo/group/service/GroupServiceTest.java, backend/src/test/java/com/woowacourse/momo/member/service/MemberServiceTest.java, backend/src/test/java/com/woowacourse/momo/participant/controller/ParticipantControllerTest.java
=> [BE] 검색 기능 구현

frontend/src/components/Header/User/index.tsx, frontend/src/components/Header/index.tsx, frontend/src/components/MyInformation/Info/Basic/index.tsx, frontend/src/components/MyInformation/Info/OAuth/index.tsx, frontend/src/components/MyInformation/Withdrawal/index.tsx
- #281 
- access token으로 사용자 정보를 요청하는 부분의 위치 수정
closed #281
=> [FE] 새로고침 시 자동 로그아웃되는 오류 해결

frontend/src/apis/request/auth.ts, frontend/src/apis/request/group.ts, frontend/src/apis/request/user.ts, frontend/src/components/Header/User/index.tsx, frontend/src/components/Header/index.tsx, frontend/src/components/Login/index.tsx, frontend/src/components/MyInformation/Withdrawal/index.tsx, frontend/src/pages/Auth/index.tsx, frontend/src/store/states.ts, frontend/src/types/user.ts, frontend/src/utils/token.ts
- #293 
- 로그인 시 리프레시 토큰을 세션에 저장
- 액세스 토큰 만료 시 리프레시 토큰을 사용하여 새롭게 발급받아 저장
closed #293
=> [FE] 리프레시 토큰 적용

frontend/src/components/SearchSection/SearchForm/index.styled.ts, frontend/src/components/SearchSection/SearchForm/index.tsx
- #300 
- 입력 input과 버튼 자체를 폼으로 감싸 검색을 submit 이벤트에 달도록 변경
closed #300
=> [FE] 모임 검색 시 엔터를 입력해도 검색되도록 추가

frontend/src/components/GroupEdit/index.tsx, frontend/webpack/webpack.development.js
- #304 
early return 조건 오류로 잘못된 값을 참조 하고 있었음
조건 변경으로 해결
closed #304
=> [FE] groupDetail 정보 로드 오류 해결

backend/src/main/java/com/woowacourse/momo/auth/service/TokenService.java, backend/src/main/java/com/woowacourse/momo/member/domain/Member.java, backend/src/main/java/com/woowacourse/momo/member/service/MemberService.java, backend/src/main/java/com/woowacourse/momo/participant/controller/ParticipantController.java, backend/src/test/java/com/woowacourse/momo/auth/controller/AuthControllerTest.java, backend/src/test/java/com/woowacourse/momo/auth/domain/TokenRepositoryTest.java, backend/src/test/java/com/woowacourse/momo/auth/service/AuthServiceTest.java, backend/src/test/java/com/woowacourse/momo/group/controller/GroupControllerTest.java, backend/src/test/java/com/woowacourse/momo/group/domain/duration/DurationTest.java, backend/src/test/java/com/woowacourse/momo/group/domain/group/GroupRepositoryTest.java, backend/src/test/java/com/woowacourse/momo/group/domain/group/GroupTest.java, backend/src/test/java/com/woowacourse/momo/group/service/GroupServiceTest.java, backend/src/test/java/com/woowacourse/momo/member/controller/MemberControllerTest.java, backend/src/test/java/com/woowacourse/momo/member/service/MemberFindServiceTest.java, backend/src/test/java/com/woowacourse/momo/member/service/MemberServiceTest.java
issue #296 
일단은 도메인과 서비스 부분에 대한 누락된 테스트를 작성하였습니다.
컨트롤러 부분은 작업하지 않았는데, 컨트롤러 부분도 에러에 대한 테스트를 작성해 둘까요?
=> [BE] 누락된 테스트 추가 작업

backend/src/main/resources/application-dev.yml, backend/src/main/resources/application-local.yml, backend/src/main/resources/application-prod.yml, backend/src/main/resources/application-test.yml, backend/src/test/resources/application.yml
- #294 
프론트 백엔드 개발서버 구축
프론트 개발서버 url: [dev.moyeora.site](dev.moyeora.site)
백엔드 api 요청 url: dev-api.moyeora.site
현재 개발﹒배포 서버로 같이 사용하던 서버를 분리
- 백엔드는 profile을 통해 prod, dev, local 프로파일을 만들어 각각의 실행환경 분리
오늘 하루~
=> [BE] 개발 서버 구축 및 실행환경 분리

backend/src/main/java/com/woowacourse/momo/group/domain/calendar/Calendar.java, backend/src/main/java/com/woowacourse/momo/group/domain/calendar/Deadline.java, backend/src/main/java/com/woowacourse/momo/group/domain/calendar/Duration.java, backend/src/main/java/com/woowacourse/momo/group/domain/calendar/Schedule.java, backend/src/main/java/com/woowacourse/momo/group/domain/calendar/Schedules.java, backend/src/test/java/com/woowacourse/momo/fixture/GroupFixture.java, backend/src/test/java/com/woowacourse/momo/fixture/calendar/DeadlineFixture.java, backend/src/test/java/com/woowacourse/momo/fixture/calendar/DurationFixture.java, backend/src/test/java/com/woowacourse/momo/fixture/calendar/ScheduleFixture.java, backend/src/test/java/com/woowacourse/momo/fixture/calendar/datetime/DateFixture.java, backend/src/test/java/com/woowacourse/momo/fixture/calendar/datetime/DateTimeFixture.java, backend/src/test/java/com/woowacourse/momo/fixture/calendar/datetime/TimeFixture.java, backend/src/test/java/com/woowacourse/momo/group/controller/GroupControllerTest.java, backend/src/test/java/com/woowacourse/momo/group/domain/calendar/CalendarTest.java, backend/src/test/java/com/woowacourse/momo/group/domain/calendar/DeadlineTest.java, backend/src/test/java/com/woowacourse/momo/group/domain/calendar/DurationTest.java, backend/src/test/java/com/woowacourse/momo/group/domain/calendar/ScheduleTest.java, backend/src/test/java/com/woowacourse/momo/group/domain/calendar/SchedulesTest.java, backend/src/test/java/com/woowacourse/momo/group/domain/group/GroupFindRepositoryTest.java, backend/src/test/java/com/woowacourse/momo/group/domain/group/GroupRepositoryTest.java, backend/src/test/java/com/woowacourse/momo/group/domain/group/GroupTest.java, backend/src/test/java/com/woowacourse/momo/group/service/GroupFindServiceTest.java, backend/src/test/java/com/woowacourse/momo/group/service/GroupServiceTest.java, backend/src/test/java/com/woowacourse/momo/member/service/MemberServiceTest.java, backend/src/test/java/com/woowacourse/momo/participant/controller/ParticipantControllerTest.java, backend/src/test/java/com/woowacourse/momo/participant/domain/ParticipantRepositoryTest.java, backend/src/test/java/com/woowacourse/momo/participant/domain/ParticipantsTest.java, backend/src/test/java/com/woowacourse/momo/participant/service/ParticipantServiceTest.java
핵심적으로 볼 내용은 아래 커밋입니당
https://github.com/woowacourse-teams/2022-momo/pull/319/commits/9de8b78947c1ec167568201bd127581df705b469
=> [BE] Calendar 도메인 패키지 리팩터링

frontend/src/components/ConfirmPassword/index.styled.ts, frontend/src/components/GroupEdit/Inputs/index.styled.ts, frontend/src/components/GroupEdit/Inputs/index.tsx, frontend/src/components/GroupEdit/index.styled.ts, frontend/src/components/GroupEdit/index.tsx, frontend/src/components/Login/index.styled.ts, frontend/src/components/Signup/index.styled.ts, frontend/src/hooks/useCreateState.ts, frontend/src/pages/Detail/Content/index.styled.ts, frontend/src/pages/Detail/Content/index.tsx, frontend/src/pages/Detail/SideBar/Info/ControlButton/index.styled.ts, frontend/src/pages/Detail/SideBar/Info/ControlButton/index.tsx, frontend/src/pages/Detail/SideBar/Info/index.styled.ts, frontend/src/pages/Detail/SideBar/Info/index.tsx, frontend/src/pages/Detail/SideBar/Participants/index.styled.ts, frontend/src/pages/Detail/SideBar/Participants/index.tsx, frontend/src/pages/Detail/SideBar/index.tsx, frontend/src/pages/Detail/index.styled.ts, frontend/src/pages/Main/Category/index.styled.ts, frontend/src/pages/Main/SearchSection/index.styled.ts, frontend/src/pages/Main/index.tsx, frontend/src/styles/global.tsx
- #326 
- 이후의 개발을 위해 프로젝트 전반적으로 리팩토링 진행
- 메인, 모임 상세, 404 페이지, 모임 수정 모달 리팩토링
closed #326
=> [FE] 메인, 상세, 수정 페이지 리팩토링

backend/src/main/java/com/woowacourse/momo/group/controller/dto/request/GroupRequestAssembler.java
https://github.com/woowacourse-teams/2022-momo/issues/332
=> [BE] 개발서버 배포가 실패하는 이슈

frontend/package.json, frontend/src/assets/svg/pencil.svg, frontend/src/components/Calendar/index.styled.ts, frontend/src/components/Calendar/index.tsx, frontend/src/components/Card/index.styled.ts, frontend/src/components/Card/index.tsx, frontend/src/components/GroupEdit/Inputs/index.styled.ts, frontend/src/components/Header/User/index.styled.ts, frontend/src/components/Modal/index.styled.ts, frontend/src/components/Modal/index.tsx, frontend/src/components/SearchForm/index.tsx, frontend/src/components/Snackbar/index.styled.ts, frontend/src/components/TopButton/index.styled.ts, frontend/src/components/TopButton/index.tsx, frontend/src/hooks/useCreateState.ts, frontend/src/pages/Create/Steps/Step1/index.tsx, frontend/src/pages/Create/Steps/Step2/index.tsx, frontend/src/pages/Create/Steps/Step3/index.tsx, frontend/src/pages/Create/Steps/Step4/index.tsx, frontend/src/pages/Create/Steps/Step5/Calendar/index.tsx, frontend/src/pages/Create/Steps/Step5/index.tsx, frontend/src/pages/Create/Steps/Step6/index.tsx, frontend/src/pages/Create/Steps/Step7/index.tsx, frontend/src/pages/Create/Steps/Step8/index.tsx, frontend/src/pages/MyInformation/Info/LiveBean/index.styled.ts, frontend/src/pages/MyInformation/Info/LiveBean/index.tsx, frontend/src/pages/MyInformation/Info/index.styled.ts, frontend/src/pages/MyInformation/Info/index.tsx, frontend/src/styles/global.tsx, frontend/src/types/utils.ts
- #338 
- Layout Shift 없애기
- 리렌더링 없애기
- 모임 카드에 memo 적용
- 상태 변경 시 리렌더링 최적화
closed #338
=> [FE] 렌더링 최적화

frontend/webpack/webpack.common.js
=> [FE] webpack-bundle-analyzer 비활성화

frontend/package-lock.json, frontend/package.json, frontend/webpack/webpack.production.js
- gzip 적용
- 웹팩에 gzip 압축 설정 추가
closed #349
=> [FE] gzip 최적화

backend/src/main/java/com/woowacourse/momo/auth/domain/TokenRepository.java, backend/src/main/java/com/woowacourse/momo/auth/service/OauthService.java, backend/src/main/java/com/woowacourse/momo/group/domain/search/GroupSearchRepository.java, backend/src/test/java/com/woowacourse/momo/auth/domain/TokenRepositoryTest.java, backend/src/test/java/com/woowacourse/momo/group/domain/GroupRepositoryTest.java
- #347 
로그인 시 잘못된 정적 팩토리 메서드를 매칭하여 버그가 발생하였다.
올바른 정적 팩토리 메서드로 변경하여 해결하였다!
=> [BE] 구글 OAuth 버그 해결

frontend/.babelrc.js, frontend/package-lock.json, frontend/package.json, frontend/src/components/Header/index.tsx, frontend/src/utils/token.ts, frontend/webpack/webpack.common.js
- #377 
- 리프레시 토큰을 사용하여 액세스 토큰을 제대로 받아온 후 사용자 정보를 요청하도록 수정
- 기존에 세션 스토리지에 저장하던 토큰을 로컬 스토리지로 이전
closed #377
=> [FE] Access Token만료 후, Refresh Token을 통한 재접근 불가 오류

frontend/package-lock.json, frontend/public/mockServiceWorker.js, frontend/src/pages/Detail/SideBar/Info/ControlButton/index.tsx, frontend/src/pages/Detail/SideBar/Info/index.tsx, frontend/src/pages/Detail/SideBar/index.tsx
- #373 
- 참여 인원이 가득 찬 경우는 마감이 아니라고 판명
- 그렇기에 프론트 쪽에서 최대 인원과 현재 참여 인원을 비교하여 더 이상 참여할 수 없을 경우 참여 인원이 가득 참을 알리는 버튼 표시
closed #373
=> [FE] 마감일이 지나지 않아도 참여자 정원이 가득차면 수정/삭제할 수 없는 현상

frontend/src/pages/Detail/SideBar/Info/index.tsx, frontend/src/pages/Detail/index.tsx, frontend/src/pages/Main/index.tsx
=> [FE] 마감된 모임에도 수정 버튼이 보이는 오류 해결

frontend/src/constants/path.ts
- #410
- Rest docs 확인 후 변경된 URI 반영
closed #410
=> [FE] signup URL을 members로 변경

frontend/src/pages/Main/index.tsx, frontend/src/pages/MyGroup/index.tsx
- #421 
- 모임 목록에서 마감된 모임 필터링을 기본값으로 '사용함' 설정
closed #421
=> [FE] 모임 목록 마감된 모임 필터링 기본값 변경

frontend/src/Routes/PrivateWrapper.tsx, frontend/src/apis/request/auth.ts, frontend/src/components/Login/index.tsx, frontend/src/components/Snackbar/index.styled.ts, frontend/src/components/Snackbar/index.tsx, frontend/src/pages/Auth/index.tsx, frontend/src/pages/Detail/SideBar/Info/ControlButton/index.tsx, frontend/src/pages/Landing/@shared/index.styled.ts, frontend/src/utils/location.ts
- #422 
- 구글 로그인 시 무조건 메인 페이지로 보내주므로 이전 히스토리를 기억하여 해당 페이지로 보내주도록 추가
- 스낵바 스타일링 변경
- 로그인하지 않은 상태에서 모임 참여 시 찜할 때처럼 스낵바를 보여주도록 변경
closed #422
=> [FE] 구글 로그인 시 이전 페이지로 보내주는 기능

backend/src/main/java/com/woowacourse/momo/auth/domain/Token.java, backend/src/main/java/com/woowacourse/momo/group/controller/GroupModifyController.java, backend/src/main/java/com/woowacourse/momo/group/domain/participant/Participant.java, backend/src/main/java/com/woowacourse/momo/group/domain/participant/Participants.java, backend/src/main/java/com/woowacourse/momo/group/service/GroupModifyService.java, backend/src/main/java/com/woowacourse/momo/member/domain/Member.java, backend/src/test/java/com/woowacourse/momo/group/domain/GroupRepositoryTest.java
Fetch 전략이 기존 Eager로 되어있던 부분을 Lazy Loading을 사용하도록 변경하였습니다.
- https://github.com/woowacourse-teams/2022-momo/issues/434
=> [BE] JPA 지연 로딩 적용

backend/src/main/java/com/woowacourse/momo/MomoApplication.java
돌고 돌아.. timezone 설정하는 로직을 프로젝트에 추가했습니다..ㅎ
사유는 Duser.timezone 옵션이 동작하지 않아요..ㅜ 옵션을 걸어주었을 때와 걸어주지 않았을 때의 차이가 없었습니다.
=> [BE] timezone 문제 해결

backend/src/main/java/com/woowacourse/momo/member/service/MemberService.java, backend/src/test/java/com/woowacourse/momo/member/service/MemberServiceTest.java
=> [BE] 이미 존재하는 사용자 이름으로 수정하는 경우에 대한 유효성 검증

frontend/src/apis/request/group.ts, frontend/src/components/Card/index.tsx, frontend/src/components/ImageDropBox/index.styled.ts, frontend/src/components/ImageDropBox/index.tsx, frontend/src/components/SearchForm/index.tsx, frontend/src/constants/message.ts, frontend/src/hooks/useModal.ts, frontend/src/pages/Detail/index.tsx, frontend/src/pages/Detail/versions/@shared/index.styled.ts, frontend/src/pages/Detail/versions/Desktop/Content/EditMode/index.tsx, frontend/src/pages/Detail/versions/Desktop/ControlButton/index.tsx, frontend/src/pages/Detail/versions/Desktop/index.tsx, frontend/src/pages/Detail/versions/Mobile/ControlButton/index.tsx, frontend/src/pages/Detail/versions/Mobile/index.tsx, frontend/src/store/states.ts, frontend/src/types/condition.ts, frontend/src/types/data.ts, frontend/src/utils/category.tsx
- #473 
- 모임 상세 페이지에 썸네일 수정 및 초기화 기능 생성
- 변경된 API에 맞게 카테고리, 모임 정보 타입에 imageUrl 추가
closed #473
=> [FE] 썸네일 기능 구현

backend/build.gradle, backend/docker/dockerfile/Dockerfile
- #480 
- 이미지 생성을 위한 dockerfile생성
- 이미지 저장을 위한 private registry 구축
- 도커를 통한 CI/CD과정을 jenkins에 적용
=> [BE] 스프링 애플리케이션의 Docker🐳 화

frontend/src/components/ImageDropBox/index.tsx, frontend/src/constants/message.ts
- #494 
- 썸네일 허용 파일 형식 수정
- jpg, jpeg, png
closed #494
=> [FE] .jpg 형식의 파일을 받지 않는 에러 해결

backend/src/main/java/com/woowacourse/momo/group/infrastructure/querydsl/GroupSearchRepositoryImpl.java, backend/src/test/java/com/woowacourse/momo/group/domain/search/GroupSearchRepositoryTest.java
- 쿼리문이 잘못되어 분리했습니다~
- 테스트 검증을 구체화하였습니다~
- #486
=> [BE] 내가 참여한 모임 목록 조회에서 참여자 수 불일치 문제

frontend/src/pages/Detail/versions/Desktop/ControlButton/index.tsx, frontend/src/pages/Detail/versions/Mobile/ControlButton/index.tsx
- #508 
- 모임을 마감했을 때 모임 참여자가 아닌 모임에 대한 정보를 다시 요청하도록 수정
closed #508
=> [FE] 상세 페이지 refetch 수정

frontend/src/assets/svg/index.ts, frontend/src/constants/message.ts, frontend/src/hooks/useCreateState.ts, frontend/src/pages/Create/Navigator/index.styled.ts, frontend/src/pages/Create/Navigator/index.tsx, frontend/src/pages/Create/Steps/@shared/styled.ts, frontend/src/pages/Create/Steps/CreateSteps.tsx, frontend/src/pages/Create/Steps/Step2/index.tsx, frontend/src/pages/Create/Steps/Step4/index.tsx, frontend/src/pages/Create/index.styled.ts, frontend/src/pages/Create/index.tsx
- #491
- 생성 페이지 UI/UX 개선
closed #491
=> [FE] 생성 페이지 UI/UX 개선

frontend/src/components/ConfirmPassword/index.tsx, frontend/src/components/Modal/index.tsx, frontend/src/hooks/useCreateState.ts, frontend/src/hooks/useKakaoMap.ts, frontend/src/pages/Create/Steps/@shared/styled.ts, frontend/src/pages/Create/Steps/Step1/index.tsx, frontend/src/pages/Create/Steps/Step2/index.tsx, frontend/src/pages/Create/Steps/Step4/index.tsx, frontend/src/pages/Create/index.tsx, frontend/src/pages/Create/validate.test.ts, frontend/src/pages/Create/validate.ts
- #518 
- 생성 페이지 폰트 크기가 잘못 표시되는 오류 수정
- 마감일 라벨에 현재 시간보다 이전으로 설정될 경우 안내 툴팁 추가
- 상세 페이지에서 지도를 클릭하면 카카오맵으로 이동하여 표시하는 기능 추가
- 중복 코드 삭제 및 과도한 크기의 함수 분리 (리팩토링)
closed #518
=> [FE] 생성 페이지 폰트 크기 수정

frontend/src/pages/Main/index.tsx, frontend/src/pages/MyGroup/index.tsx
- #520 
- 페이지 번호를 업데이트하는 useEffect의 디펜던시를 data → isFetching으로 수정
closed #520
=> [FE] 무한 스크롤 요청 에러 해결

README.md
- #490 
- 페이지 디자인이 바뀜에 따라 README 이미지 최신화
closed #490
=> [ALL] README 이미지 최신화
